name: CI with MySQL

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: database@9440672439
          MYSQL_DATABASE: spring
          MYSQL_USER: root
          MYSQL_PASSWORD: database@9440672439
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/spring
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: database@9440672439
